version: '3'
services:
  web:
#    image: localhost:5000/ist_web
    build: .
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.4"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    command: uwsgi --http :80 --module MTproject.wsgi
#    command: uwsgi --ini mysite_uwsgi.ini
    volumes:
      - .:/app
    networks:
      - webnet
#  visualizer:
#    image: dockersamples/visualizer:stable
#    ports:
#      - "8080:8080"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    deploy:
#      placement:
#        constraints: [node.role == manager]
#    networks:
#      - webnet
networks:
  webnet: