# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_auto_20160827_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyWord', models.CharField(max_length=200)),
            ],
        ),
    ]
